-- ==============================================================================
-- Database Schema for LLM-Based Threat Intelligence Gathering System
-- ==============================================================================

-- Table 1: raw_items
-- Purpose: Stores the raw, unprocessed data collected from various threat feeds 
--          (e.g., NVD, AlienVault OTX, Exploit-DB RSS).
CREATE TABLE IF NOT EXISTS raw_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,               -- Source of the data (e.g., 'NVD', 'AlienVault')
    title TEXT,                         -- Title of the article or threat report
    description TEXT,                   -- Main content or summary of the threat
    source_url TEXT,                    -- Original URL of the report
    published_date TEXT,                -- Date the report was officially published
    collected_at TEXT NOT NULL,         -- UTC Timestamp when the data was scraped by the collector
    processed INTEGER DEFAULT 0,        -- Workflow flag: 0 = Unprocessed/Raw, 1 = Cleaned & Encapsulated
    raw TEXT,                           -- Full raw JSON payload or HTML content (stored as string)
    dedup_key TEXT UNIQUE               -- Unique hash (e.g., SHA-256) to prevent duplicate entries
);

-- Table 2: entities
-- Purpose: Stores deterministic Indicators of Compromise (IOCs) and named entities 
--          extracted via Regex and spaCy (e.g., IPs, Domains, CVEs, Malware Names).
CREATE TABLE IF NOT EXISTS entities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_id INTEGER NOT NULL,         -- Foreign key linking back to the original article in raw_items
    entity_type TEXT NOT NULL,          -- Category of the entity (e.g., 'CVE', 'IPv4', 'Malware', 'Threat_Actor')
    entity_value TEXT NOT NULL,         -- The actual extracted value (e.g., 'CVE-2024-1234', '192.168.1.1')
    extracted_at TEXT NOT NULL,         -- UTC Timestamp of extraction
    FOREIGN KEY (source_id) REFERENCES raw_items(id) ON DELETE CASCADE
);

-- Table 3: ttp_mappings
-- Purpose: Stores the MITRE ATT&CK Tactics and Techniques identified and mapped by the local Llama 3 model.
CREATE TABLE IF NOT EXISTS ttp_mappings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_id INTEGER NOT NULL,         -- Foreign key linking back to the original article in raw_items
    tactic_name TEXT NOT NULL,          -- MITRE Tactic Category (e.g., 'Initial Access', 'Execution')
    technique_id TEXT NOT NULL,         -- Official MITRE Technique ID (e.g., 'T1190')
    technique_name TEXT NOT NULL,       -- Official MITRE Technique Name (e.g., 'Exploit Public-Facing Application')
    justification TEXT,                 -- Sentence from the text used by AI to justify this mapping (prevents hallucinations)
    mapped_at TEXT NOT NULL,            -- UTC Timestamp of when the AI processed this mapping
    FOREIGN KEY (source_id) REFERENCES raw_items(id) ON DELETE CASCADE
);

-- Table 4: reports
-- Purpose: Stores the final AI-generated analytical summaries and tracks the Human-in-the-Loop (HITL) review status.
CREATE TABLE IF NOT EXISTS reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_id INTEGER NOT NULL,         -- Foreign key linking back to the original article in raw_items
    summary TEXT NOT NULL,              -- The executive summary narrative generated by the LLM
    hitl_status TEXT DEFAULT 'pending', -- Human-in-the-loop review status: 'pending', 'approved', or 'rejected'
    created_at TEXT NOT NULL,           -- UTC Timestamp of report generation
    reviewed_at TEXT,                   -- UTC Timestamp of when a human analyst reviewed the report via CLI
    FOREIGN KEY (source_id) REFERENCES raw_items(id) ON DELETE CASCADE
);